---
service: kyivmural-app
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: test
  region: eu-central-1
  stackTags:
    Name: Kyivmural-App
    Version: 0.2.6
    Application: Kyivmural
    Component: App
  iam:
    role:
      statements:
        - Effect: Allow
          Action: execute-api:Invoke
          Resource:
            - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${env:KYIVMURAL_API_ID}/${env:KYIVMURAL_API_STAGE}/GET/*"
  apiGateway:
    shouldStartNameWithService: true

functions:
  kyivmural-app:
    handler: wsgi_handler.handler
    environment:
      KYIVMURAL_API_ENDPOINT: ${env:KYIVMURAL_API_ENDPOINT}
      DEFAULT_LANG_CODE: ${env:DEFAULT_LANG_CODE}
      GOOGLE_MAPS_API_KEY: ${env:GOOGLE_MAPS_API_KEY}
      GOOGLE_ANALYTICS_ID: ${env:GOOGLE_ANALYTICS_ID}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  wsgi:
    app: app.app

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**
    - Pipfile
    - Pipfile.lock
    - readme.md
    - package-lock.json
    - package.json
    - tox.ini
    - VERSION
