---
service: kyivmural

provider:
  name: aws
  runtime: python3.8

functions:
  app:
    handler: wsgi_handler.handler
    environment:
      KYIVMURAL_API_ENDPOINT: dummy
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

custom:
  wsgi:
    app: app.app
    pythonBin: python
    packRequirements: false
  pythonRequirements:
    dockerPip: non-linux

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**
    - Pipfile
    - Pipfile.lock
    - readme.md
    - package-lock.json