name: PR cleanup
on:
  pull_request:
    types: [closed]

jobs:
  delete-pr-stack:
    name: Delete PR stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KYIVMURAL_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KYIVMURAL_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_KYIVMURAL_REGION }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - name: Remove PR stack
        uses: serverless/github-action@master
        with:
          args: -c "serverless remove --stage pr-${{ github.event.number }}"
          entrypoint: /bin/bash
        env:
          KYIVMURAL_API_ENDPOINT: ${{ secrets.KYIVMURAL_API_ENDPOINT }}
          KYIVMURAL_API_ID: ${{ secrets.KYIVMURAL_API_ID }}
          KYIVMURAL_API_STAGE: ${{ secrets.KYIVMURAL_API_STAGE }}
          DEFAULT_LANG_CODE: ${{ secrets.DEFAULT_LANG_CODE }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
