name: PR pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  python-linter:
    name: Python Lint
    runs-on: ubuntu-latest
    env:
      SOURCE_FOLDER: kyivmural
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: python -m pip install --upgrade pip wheel pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Add current working dir to PYTHONPATH
        run: echo "PYTHONPATH=${PYTHONPATH}:src" >> $GITHUB_ENV
      - name: Pylint
        run: pipenv run pylint $SOURCE_FOLDER
      - name: Pycodestyle
        run: pipenv run pycodestyle $SOURCE_FOLDER
      - name: Flake8
        run: pipenv run flake8 $SOURCE_FOLDER
      - name: Isort
        run: pipenv run isort $SOURCE_FOLDER --profile black --check-only
      - name: Black
        run: pipenv run black $SOURCE_FOLDER --check

  yaml-linter:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3.0.0
        with:
          file_or_dir: serverless.yml

  provision-pr-stack:
    name: Provision PR stack
    needs:
      - yaml-linter
      - python-linter
    runs-on: ubuntu-latest
    env:
      BRANCH: pr-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KYIVMURAL_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KYIVMURAL_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_KYIVMURAL_REGION }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: python -m pip install --upgrade pip wheel pipenv
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - name: Provision PR stack
        uses: dhollerbach/github-action-serverless-with-python-requirements@master
        with:
          args: --stage $BRANCH
        env:
          KYIVMURAL_API_ENDPOINT: ${{ secrets.KYIVMURAL_API_ENDPOINT }}
          KYIVMURAL_API_ID: ${{ secrets.KYIVMURAL_API_ID }}
          KYIVMURAL_API_STAGE: ${{ secrets.KYIVMURAL_API_STAGE }}
          DEFAULT_LANG_CODE: ${{ secrets.DEFAULT_LANG_CODE }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          GOOGLE_ANALYTICS_ID: bum
