name: Version & Release

on:
  push:
    branches:
      - master

jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Read version
      id: read_version
      run: |
        version=`cat VERSION`
        echo "version: $version"
        echo "##[set-output name=version;]v$version"
    - uses: mukunku/tag-exists-action@v1.0.0
      id: check_tag
      with:
        tag: ${{ steps.read_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      if: ${{ steps.check_tag.outputs.exists == 'false' }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.read_version.outputs.version }}
        name: ${{ steps.read_version.outputs.version }}
        body: Version ${{ steps.read_version.outputs.version }}
        draft: false
        prerelease: false
    - name: Release already exists
      if: ${{ steps.check_tag.outputs.exists == 'true' }}
      run: echo "Release ${{ steps.read_version.outputs.version }} already exists"
